- name: Enter the variable values using prompt and display
  hosts:  local
  connection: local
  vars_prompt:
    - name: course
      prompt: Please enter course name
      private: false
    - name: duration
      prompt: Please enter duration of the course
      private: false
    - name: trainer
        prompt: Enter the trainer name       
  tasks:  
    - name: Print the variable values
      ansible.builtin.debug:
        msg:  "Course is {{ course}} and the duration is {{ duration }} and the trainer name is {{ trainer}}"

    